version: ~> 1.0
dist: focal
language: python


script:
  - make test

python:
  - 3.10
  - 3.11
  - 3.12
  - 3.13
    script:
      - make test
      # 開発環境と同じバージョンではlintを実行する
      - make lint

install:
  - pip install uv
  # travis_retryを使う理由: インストール時にtimeoutで失敗しないようにするため
  - travis_retry uv sync --all-groups

branches:
  only:
  - main
env:
  # 依存パッケージのダウンロード時にタイムアウトしないようにするため、タイムアウト時間を指定する
  - PIP_DEFAULT_TIMEOUT=300
